---
title: "Course resources"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<!-- <p style="color: #ba5e00"><b>TO UPDATE THIS PAGE:</b> Open and edit the <b>resources.Rmd</b> file, in the project root, to delete this placeholder text and customize with your own!</p> -->

All lecture slides, readings, and labs will be posted here each week. Assignments will be mentioned here, but all assignments will be posted, submitted, and graded through Github Classrooms.

### Week 0

- **Slides**: Course intro [html](slides/01-intro/01-intro.html) [pdf](slides/01-intro/01-intro.pdf)

- **Reading:** 
  + [Preface, Chapters 1-2](https://openintro-ims.netlify.app/preface.html), _Introduction to Modern Statistics_
  + (Optional) [Gender Shades](http://gendershades.org/)
  + (Optional) [RCTs](https://www.youtube.com/watch?v=0zvrGiPkVcs)

- **Assignment:** Assignment 1 posted 9/28; due 10/09, 5pm (note: usually will be Fridays, this deadline allows you more time to get set up on GitHub Classroom)

### Week 1

- **Slides**: Summary statistics [html](slides/02-summstats/02-summstats.html) [pdf](slides/02-summstats/02-summstats.pdf)

- **Reading:** 
  + [Chapters 4-6](https://openintro-ims.netlify.app/data-design.html), _Introduction to Modern Statistics_

- **Discussion Section (Wednesday)**: EDS 222 Lab setup and Github Classrooms demo (taught by TA, Sandy Sum)
  + [Lab markdown](labs/01-week-one/week-1-discussion.Rmd)
  + [Lab html](labs/01-week-one/week-1-discussion.html)
  + [`_common.R` setup script](labs/_common.R) 

- **Lab (Thursday)**: Summarizing categorical and numerical data in `R`
  + [Lab markdown](labs/01-week-one/week-1-lab.Rmd)
  + [Lab answers](labs/01-week-one/week-1-lab-answers.Rmd)
  + [Lab answers in html](labs/01-week-one/week-1-lab-answers.html)

- **Assignment:** Assignment 1 due 10/09, 5pm 


### Week 2

- **Slides**: Ordinary Least Squares [html](slides/03-ols/03-ols.html) [pdf](slides/03-ols/03-ols.pdf)

- **Reading:** 
  + [Chapter 7](https://openintro-ims.netlify.app/model-slr), _Introduction to Modern Statistics_

- **Discussion Section (Wednesday)**: Law of Large Numbers, simulation in `R`
  + [HW 1 Answers](https://www.dropbox.com/scl/fi/38irxdig9ln9bfk38jhk3/assignment-01-answers.Rmd?rlkey=s5wk2ebdemsgkzehizzipe8l4&dl=0)

- **Lab (Thursday)**: Correlations and ordinary least squares in `R`
  + [Lab markdown](labs/02-week-two/week-2-lab.Rmd)
  + [Lab answers](labs/02-week-two/week-2-lab-answers.Rmd)
  + [Lab answers in html](labs/02-week-two/week-2-lab-answers.html)

- **Assignment:** Assignment 1 due 10/09, 5pm. Assignment 2 posted 10/10 and due 10/20 at 5pm.

<!--
- **Reading:** 
  

- **Lab:** [setup script](https://www.dropbox.com/s/2pwolalmlai8n5m/_common.R?dl=0), [markdown](labs/02-week-two/week-2-lab.Rmd), [answers](labs/02-week-two/week-2-lab-answers.Rmd), [answers in html](labs/02-week-two/week-2-lab-answers.html). Note: all files also on Github [here](https://github.com/tcarleton/EDS-222-stats)
  
- **Assignment:** Assignment 2 posted 9/30; due 10/7, 5pm
-->

### Week 3

- **Slides 04**: Ordinary Least Squares, continued [html](slides/04-ols-contd/04-ols-contd.html) [pdf](slides/04-ols-contd/04-ols-contd.pdf) 

- **Reading:** 
  + [Chapter 8](https://openintro-ims.netlify.app/model-mlr), _Introduction to Modern Statistics_
  + [Optional/Extra: Ch 10](https://openintro-ims.netlify.app/model-application.html), _Introduction to Modern Statistics_

- **Discussion Section (Wednesday)**: Materials to be distributed in class

- **Lab (Thursday):** OLS in `R`, continued (to be posted)<!-- [markdown](labs/04-week-four/week-4-lab.Rmd), [answers](labs/04-week-four/week-4-lab-answers.Rmd), [answers in html](labs/04-week-four/week-4-lab-answers.html). 
-->

- **Final project guidelines:** [link](https://www.dropbox.com/scl/fi/3g8oidwst58u2ie0xy9mx/EDS222_final_project_guidelines.pdf?rlkey=urgev9ixns18yjvw305ojgo93&dl=0)

- **Assignment:** Assignment 2 due 10/20, 5pm 

<!--
### Week 4

- **Slides 04**: Ordinary Least Squares, continued [html](slides/04-ols-contd/04-ols-contd.html) [pdf](slides/04-ols-contd/04-ols-contd.pdf) 

- **Reading:** 
  + [Chapter 8](https://openintro-ims.netlify.app/data-design.html), _Introduction to Modern Statistics_
  + [Optional/Extra: Ch 10](https://openintro-ims.netlify.app/model-application.html), _Introduction to Modern Statistics_

- **Lab:** OLS in `R`, continued [markdown](labs/04-week-four/week-4-lab.Rmd), [answers](labs/04-week-four/week-4-lab-answers.Rmd), [answers in html](labs/04-week-four/week-4-lab-answers.html). 
  
- **Assignment:** Assignment 2 due 10/13, 9am
-->
<!--
### Week 5

- **Slides 05**: Multiple linear regression and interaction models [html](slides/05-multiplereg/05-multiplereg.html) [pdf](slides/05-multiplereg/05-multiplereg.pdf)

- **Reading:** 
  + [Chapter 8](https://openintro-ims.netlify.app/data-design.html), _Introduction to Modern Statistics_
  + Note that interaction models are not covered in _IMS_. [This](http://www.jkarreth.net/files/RPOS517_Day11_Interact.html) is a helpful resource that covers interaction models conceptually and shows how to code them up in `R` (note that we will cover the coding in Thursday's lab and please ignore anything after the subsection titled "Obtaining standard errors for marginal effects")

- **Lab:** Interaction models in `R` [markdown](labs/05-week-five/week-5-lab.Rmd), [answers](labs/05-week-five/week-5-lab-answers.Rmd), [answers in html](labs/05-week-five/week-5-lab-answers.html). 
  
- **Assignment:** Assignment 3 posted 10/18, see lecture slides for details on timing and grading 

- **Extra exam study material:** Here is an example of how you can evaluate the plausibility of OLS Assumption #4, which is necessary to ensure that OLS is the lowest variance estimator of all the unbiased estimators: [html](labs/05-week-five/example_OLS_assumptions.html), [markdown](labs/05-week-five/example_OLS_assumptions.Rmd)
-->
<!--
### Week 6

- Review \& Midterm Exam

- **Assignment 3 answer key:** [html](labs/assignment-03-answers.html) [rmd](labs/assignment-03-answers.Rmd)

-->
<!--
### Week 7

- **Slides 07**: Logistic regression and other nonlinear models [html](slides/07-nonlinearmodels/07-nonlinearmodels.html) [pdf](slides/07-nonlinearmodels/07-nonlinearmodels.pdf)

- **Reading:** 
  + [Chapter 9](https://openintro-ims.netlify.app/model-logistic.html), _Introduction to Modern Statistics_

- **Lab:** Logistic regressions in `R` [markdown](labs/07-week-seven/week-7-lab.Rmd), [answers](labs/07-week-seven/week-7-lab-answers.Rmd), [answers in html](labs/07-week-seven/week-7-lab-answers.html) 
  
- **Assignment:** Final project proposal due November 10, 9am. Final project guidelines [here](labs/EDS222_final_project_guidelines.pdf)
-->
<!--
### Week 8

- **Slides 08:** Inference and hypothesis testing [html](slides/08-inference/08-inference.html) [pdf](slides/08-inference/08-inference.pdf)

- **Reading:** 
  + [Chapters 13, 19.2](https://openintro-ims.netlify.app/foundations-mathematical.html)
  
 + [Chapters 2, 3](https://otexts.com/fpp3/), _Forecasting: Principles and Practice_ 

- **Lab:** Inference and hypothesis testing in `R` [markdown](labs/08-week-eight/week-8-lab.Rmd), [answers](labs/08-week-eight/week-8-lab-answers.Rmd), [answers in html](labs/08-week-eight/week-8-lab-answers.html)

- **Assignment:** Assignment 4 (posted 11/9, due 11/23)

- **Exam answer key:** Available [here](exams/EDS222_midterm_2022_ANSWERKEY.pdf)
-->
<!--
### Week 9

- **Slides 09:** Time series analysis [html](slides/09-timeseries/09-timeseries.html) [pdf](slides/09-timeseries/09-timeseries.pdf)

- **Slides 10:** Spatial interpolation and kriging [html](slides/10-kriging/10-kriging.html) [pdf](slides/10-kriging/10-kriging.pdf) 

- **Reading:** Chapters 2 and 3 in [Hyndman & Athanasopoulos](https://otexts.com/fpp3/)

- **Lab:** Kriging in `R` [**delayed** to Week 10]
  
- **Assignment:** Assignment 4: Hypothesis testing and time series analysis (due 11/23, 5pm)
-->
<!--
### Week 10

- **Slides 10:** Spatial interpolation and kriging [html](slides/10-kriging/10-kriging.html) [pdf](slides/10-kriging/10-kriging.pdf) 

- **Lab:** Kriging in `R` [**delayed** to Week 11]  [data](https://www.dropbox.com/s/ganv3ofxjjobgds/week-ten-data.RDS?dl=0) [markdown](labs/08-week-eight/week-8-lab.Rmd), [answers](labs/08-week-eight/week-8-lab-answers.Rmd), [answers in html](labs/08-week-eight/week-8-lab-answers.html).
  
- **Assignment:** Assignment 4: Hypothesis testing and time series analysis (due 11/23, 5pm)

-->
<!--
### Week 11

- **Lab (Tuesday 11/29):** Kriging in `R` [data](https://www.dropbox.com/s/ganv3ofxjjobgds/week-ten-data.RDS?dl=0) [markdown](labs/10-week-ten/week-10-lab.Rmd), [answers](labs/10-week-ten/week-10-lab-answers.Rmd), [answers in html](labs/10-week-ten/week-10-lab-answers.html). 
  
- **Slides (Thursday 12/1)**: Applying environmental data science (lots of stats!) to climate change equity research and policy [pdf](https://www.dropbox.com/s/c75fbsi8pq4m2c5/Climate_equity__EDS_222_lecture.pdf?dl=0) 

- **Further reading for those interested**: [Rode et al. (2021)](https://www.nature.com/articles/s41586-021-03883-8); [Carleton et al. (2022)](https://academic.oup.com/qje/article-abstract/137/4/2037/6571943); [Carleton \& Greenstone (2022)](https://doi.org/10.1086/720988)

- **Final projects!** Presentations: 12/6 [TBD on Zoom vs in-person]
-->
<!--
-   RStudio's [`distill` website](https://rstudio.github.io/distill/)
-   Inspiration and examples from the [distillery](https://distillery.rbind.io/showcase.html)
-->
